"""Concrete dependency-light generators for universal project automation."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

from notebook_workflow.generators.base import ProjectGenerator
from notebook_workflow.models import ProjectPlan, ProjectRequest, ProjectType
from notebook_workflow.providers import AIProvider, build_provider


class BaseGenerator(ProjectGenerator):
    def __init__(self, project_type: ProjectType) -> None:
        self.project_type = project_type

    def _write(self, root: Path, files: dict[str, str]) -> list[str]:
        root.mkdir(parents=True, exist_ok=True)
        written: list[str] = []
        for name, content in files.items():
            path = root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            written.append(name)
        return written

    def _common(self, request: ProjectRequest, plan: ProjectPlan) -> dict[str, str]:
        manifest = {
            "name": request.metadata.get("name", "generated-project"),
            "project_type": plan.project_type.value,
            "description": request.prompt,
            "features": list(request.metadata.get("features", [])),
        }
        return {
            "project.json": json.dumps(manifest, indent=2) + "\n",
            "tests/test_smoke.py": "def test_generated_project_smoke():\n    assert True\n",
            "README.md": f"# Generated {plan.project_type.value} project\n\n{request.prompt}\n",
        }


class JupyterGenerator(BaseGenerator):
    def __init__(self) -> None:
        super().__init__(ProjectType.JUPYTER)

    def generate(self, request: ProjectRequest, plan: ProjectPlan, output_dir: Path) -> Iterable[str]:
        cells = [
            {"cell_type": "markdown", "metadata": {}, "source": [f"# {request.prompt}\n", "\n", "Generated by Automatic Jupyter Workflow."]},
            {"cell_type": "markdown", "metadata": {}, "source": ["## Notes\n", "Explain the concept, assumptions, and observations here."]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": ["print('Project notebook is ready.')\n"]},
        ]
        notebook = {
            "cells": cells,
            "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python", "version": "3"}},
            "nbformat": 4,
            "nbformat_minor": 5,
        }
        files = self._common(request, plan)
        files["notebook.ipynb"] = json.dumps(notebook, indent=2) + "\n"
        return self._write(output_dir, files)


class DataScienceGenerator(BaseGenerator):
    def __init__(self) -> None:
        super().__init__(ProjectType.DATA_SCIENCE)

    def generate(self, request: ProjectRequest, plan: ProjectPlan, output_dir: Path) -> Iterable[str]:
        files = self._common(request, plan)
        files.update({
            "src/main.py": """import csv\nfrom pathlib import Path\n\ndef summarize_csv(path: str) -> dict[str, float]:\n    with Path(path).open(newline='', encoding='utf-8') as handle:\n        rows = list(csv.DictReader(handle))\n    numeric = {}\n    for key in rows[0] if rows else {}:\n        values = [float(row[key]) for row in rows if row.get(key, '').strip()]\n        if values:\n            numeric[key] = sum(values) / len(values)\n    return numeric\n\nif __name__ == '__main__':\n    print(summarize_csv('data/sample.csv'))\n""",
            "data/sample.csv": "id,value\n1,10\n2,20\n3,30\n",
            "tests/test_data_science.py": "from src.main import summarize_csv\n\n\ndef test_summarize_csv(tmp_path):\n    path = tmp_path / 'data.csv'\n    path.write_text('id,value\\n1,10\\n2,20\\n', encoding='utf-8')\n    assert summarize_csv(str(path)) == {'id': 1.5, 'value': 15.0}\n",
        })
        return self._write(output_dir, files)


class MachineLearningGenerator(BaseGenerator):
    def __init__(self) -> None:
        super().__init__(ProjectType.MACHINE_LEARNING)

    def generate(self, request: ProjectRequest, plan: ProjectPlan, output_dir: Path) -> Iterable[str]:
        files = self._common(request, plan)
        files.update({
            "src/__init__.py": "",
            "src/model.py": """def nearest_mean_predict(train_x, train_y, value):\n    if not train_y or len(train_x) != len(train_y):\n        raise ValueError('training data must be non-empty and aligned')\n    pairs = sorted(zip(train_x, train_y), key=lambda pair: abs(pair[0] - value))\n    return pairs[0][1]\n""",
            "src/train.py": """from src.model import nearest_mean_predict\n\ntrain_x = [0, 10, 20]\ntrain_y = [0, 1, 2]\nprint('prediction:', nearest_mean_predict(train_x, train_y, 12))\n""",
            "tests/test_model.py": "from src.model import nearest_mean_predict\n\n\ndef test_nearest_mean_predict():\n    assert nearest_mean_predict([0, 10, 20], [0, 1, 2], 12) == 1\n",
        })
        return self._write(output_dir, files)


class AIGenerator(BaseGenerator):
    def __init__(self, provider: AIProvider | None = None) -> None:
        super().__init__(ProjectType.AI)
        self.provider = provider or build_provider()

    def _ai_metadata(self, prompt: str) -> dict[str, object]:
        """Optionally turn an LLM response into bounded metadata, never code."""
        if getattr(self.provider, "name", "none") == "none":
            return {}
        try:
            raw = self.provider.generate(
                "Return ONLY JSON with keys description and features. "
                "description must be a short string; features must be an array of at most 8 short strings. "
                "Do not include code, commands, credentials, or markdown. Requirement: " + prompt
            )
            parsed = json.loads(raw)
            description = parsed.get("description")
            features = parsed.get("features")
            if not isinstance(description, str) or not isinstance(features, list):
                return {}
            safe_features = [item.strip() for item in features if isinstance(item, str) and item.strip()][:8]
            return {"description": description.strip()[:500], "features": [item[:120] for item in safe_features]}
        except (OSError, RuntimeError, ValueError, TypeError, KeyError, json.JSONDecodeError):
            return {}

    def generate(self, request: ProjectRequest, plan: ProjectPlan, output_dir: Path) -> Iterable[str]:
        files = self._common(request, plan)
        ai_metadata = self._ai_metadata(request.prompt)
        if ai_metadata:
            manifest = json.loads(files["project.json"])
            manifest["ai_assisted"] = True
            manifest["ai_metadata"] = ai_metadata
            files["project.json"] = json.dumps(manifest, indent=2) + "\n"
            files["README.md"] += "\n## AI-assisted design\n\n" + str(ai_metadata["description"]) + "\n\nFeatures:\n" + "\n".join(f"- {item}" for item in ai_metadata["features"]) + "\n"
        files.update({
            "src/__init__.py": "",
            "src/ai.py": """def classify_intent(text: str) -> str:\n    value = text.lower()\n    if any(word in value for word in ('error', 'bug', 'fail')):\n        return 'technical_support'\n    if any(word in value for word in ('learn', 'study', 'course')):\n        return 'education'\n    return 'general'\n\nif __name__ == '__main__':\n    print(classify_intent('help me study Python'))\n""",
            "tests/test_ai.py": "from src.ai import classify_intent\n\n\ndef test_classify_intent():\n    assert classify_intent('I have a bug') == 'technical_support'\n    assert classify_intent('help me study') == 'education'\n",
        })
        files["README.md"] += "\nOptional LLM providers enrich project metadata only; no API key is required for the deterministic baseline.\n"
        return self._write(output_dir, files)


class CodingGenerator(BaseGenerator):
    def __init__(self) -> None:
        super().__init__(ProjectType.CODING)

    def generate(self, request: ProjectRequest, plan: ProjectPlan, output_dir: Path) -> Iterable[str]:
        files = self._common(request, plan)
        files.update({
            "src/__init__.py": "",
            "src/main.py": """def main() -> None:\n    print('Coding project ready.')\n\nif __name__ == '__main__':\n    main()\n""",
            "tests/test_main.py": "from src.main import main\n\n\ndef test_main_callable():\n    assert callable(main)\n",
        })
        return self._write(output_dir, files)


class WebGenerator(BaseGenerator):
    def __init__(self) -> None:
        super().__init__(ProjectType.WEB)

    def generate(self, request: ProjectRequest, plan: ProjectPlan, output_dir: Path) -> Iterable[str]:
        files = self._common(request, plan)
        files.update({
            "index.html": "<!doctype html>\n<html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Generated App</title><link rel='stylesheet' href='style.css'></head><body><main><h1>Generated Web Project</h1><p>Ready for your requirements.</p></main><script src='app.js'></script></body></html>\n",
            "style.css": "body{font-family:system-ui,sans-serif;margin:0;padding:3rem}main{max-width:720px;margin:auto}\n",
            "app.js": "document.title = 'Universal Project Automation';\n",
            "tests/test_web_files.py": "from pathlib import Path\n\n\ndef test_web_entry_files_exist():\n    root = Path(__file__).parents[1]\n    assert (root / 'index.html').is_file()\n    assert (root / 'style.css').is_file()\n    assert (root / 'app.js').is_file()\n",
        })
        return self._write(output_dir, files)


class AppGenerator(BaseGenerator):
    def __init__(self) -> None:
        super().__init__(ProjectType.APP)

    def generate(self, request: ProjectRequest, plan: ProjectPlan, output_dir: Path) -> Iterable[str]:
        files = self._common(request, plan)
        files["App.js"] = "import React from 'react';\nimport { SafeAreaView, Text } from 'react-native';\n\nexport default function App() {\n  return <SafeAreaView><Text>Generated app ready.</Text></SafeAreaView>;\n}\n"
        files["package.json"] = json.dumps({
            "name": "generated-app",
            "version": "1.0.0",
            "private": True,
            "main": "node_modules/expo/AppEntry.js",
            "dependencies": {"expo": "~53.0.0", "react": "19.0.0", "react-native": "0.79.2"},
        }, indent=2) + "\n"
        files["tests/test_app_files.py"] = "import json\nfrom pathlib import Path\n\n\ndef test_app_manifest_and_entrypoint():\n    root = Path(__file__).parents[1]\n    manifest = json.loads((root / 'package.json').read_text(encoding='utf-8'))\n    assert manifest['private'] is True\n    assert (root / 'App.js').is_file()\n"
        return self._write(output_dir, files)


def default_concrete_generators() -> list[ProjectGenerator]:
    return [JupyterGenerator(), DataScienceGenerator(), MachineLearningGenerator(), AIGenerator(), CodingGenerator(), WebGenerator(), AppGenerator()]
