"""Real Jupyter notebook generator with dependency-free JSON emission."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

from notebook_workflow.generators.base import ProjectGenerator
from notebook_workflow.models import ProjectPlan, ProjectRequest, ProjectType


class JupyterGenerator(ProjectGenerator):
    project_type = ProjectType.JUPYTER

    def generate(self, request: ProjectRequest, plan: ProjectPlan, output_dir: Path) -> Iterable[str]:
        output_dir.mkdir(parents=True, exist_ok=True)
        title = request.name or "Generated Jupyter Project"
        cells = [
            {"cell_type": "markdown", "metadata": {}, "source": [f"# {title}\n", "\n", request.description or "Generated by Universal Project Automation."]},
            {"cell_type": "markdown", "metadata": {}, "source": ["## Objective\n", "\n", "This notebook contains an original, runnable starter workflow."]},
            {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": ["project_name = ", repr(title), "\n", "print(f'Project: {project_name}')\n"]},
            {"cell_type": "markdown", "metadata": {}, "source": ["## Notes\n", "\n", "Add or edit cells to match the supplied assignment or project requirements."]},
        ]
        notebook = {
            "cells": cells,
            "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python"}},
            "nbformat": 4,
            "nbformat_minor": 5,
        }
        path = output_dir / f"{title.replace(' ', '_').lower()}.ipynb"
        path.write_text(json.dumps(notebook, indent=2) + "\n", encoding="utf-8")
        return [path.name]
